// lib/mock-top-transfers.ts
// Mock data for top transfers — used as fallback when the RapidAPI quota is exceeded (429)

import type { ApiRapidTopTransfer } from "@/types/api";

export const mockTopTransfers: ApiRapidTopTransfer[] = [
  {
    id: 1,
    player_name: "Kylian Mbappé",
    age: "25",
    date: "2025-06-01",
    from_club: {
      id: 101,
      name: "Paris Saint-Germain",
      logo: "https://media.api-sports.io/football/teams/85.png",
    },
    to_club: {
      id: 102,
      name: "Real Madrid",
      logo: "https://media.api-sports.io/football/teams/541.png",
    },
    fee: "Free Transfer",
    market_value: "€180.00M",
    position: "Forward",
    nationality: "France",
    photo: "",
    league: "La Liga",
    season: "2025/2026",
  },
  {
    id: 2,
    player_name: "Jude Bellingham",
    age: "22",
    date: "2025-07-15",
    from_club: {
      id: 103,
      name: "Borussia Dortmund",
      logo: "https://media.api-sports.io/football/teams/165.png",
    },
    to_club: {
      id: 102,
      name: "Real Madrid",
      logo: "https://media.api-sports.io/football/teams/541.png",
    },
    fee: "€103.00M",
    market_value: "€150.00M",
    position: "Midfielder",
    nationality: "England",
    photo: "",
    league: "La Liga",
    season: "2025/2026",
  },
  {
    id: 3,
    player_name: "Erling Haaland",
    age: "24",
    date: "2025-07-01",
    from_club: {
      id: 104,
      name: "Borussia Dortmund",
      logo: "https://media.api-sports.io/football/teams/165.png",
    },
    to_club: {
      id: 105,
      name: "Manchester City",
      logo: "https://media.api-sports.io/football/teams/50.png",
    },
    fee: "€60.00M",
    market_value: "€200.00M",
    position: "Forward",
    nationality: "Norway",
    photo: "",
    league: "Premier League",
    season: "2025/2026",
  },
  {
    id: 4,
    player_name: "Declan Rice",
    age: "26",
    date: "2025-08-05",
    from_club: {
      id: 106,
      name: "West Ham United",
      logo: "https://media.api-sports.io/football/teams/48.png",
    },
    to_club: {
      id: 107,
      name: "Arsenal",
      logo: "https://media.api-sports.io/football/teams/42.png",
    },
    fee: "€116.00M",
    market_value: "€120.00M",
    position: "Midfielder",
    nationality: "England",
    photo: "",
    league: "Premier League",
    season: "2025/2026",
  },
  {
    id: 5,
    player_name: "Harry Kane",
    age: "31",
    date: "2025-07-20",
    from_club: {
      id: 108,
      name: "Tottenham Hotspur",
      logo: "https://media.api-sports.io/football/teams/47.png",
    },
    to_club: {
      id: 109,
      name: "Bayern Munich",
      logo: "https://media.api-sports.io/football/teams/157.png",
    },
    fee: "€95.00M",
    market_value: "€110.00M",
    position: "Forward",
    nationality: "England",
    photo: "",
    league: "Bundesliga",
    season: "2025/2026",
  },
  {
    id: 6,
    player_name: "Enzo Fernández",
    age: "24",
    date: "2025-01-31",
    from_club: {
      id: 110,
      name: "Benfica",
      logo: "https://media.api-sports.io/football/teams/211.png",
    },
    to_club: {
      id: 111,
      name: "Chelsea",
      logo: "https://media.api-sports.io/football/teams/49.png",
    },
    fee: "€121.00M",
    market_value: "€85.00M",
    position: "Midfielder",
    nationality: "Argentina",
    photo: "",
    league: "Premier League",
    season: "2025/2026",
  },
  {
    id: 7,
    player_name: "Jack Grealish",
    age: "29",
    date: "2025-08-10",
    from_club: {
      id: 112,
      name: "Aston Villa",
      logo: "https://media.api-sports.io/football/teams/66.png",
    },
    to_club: {
      id: 105,
      name: "Manchester City",
      logo: "https://media.api-sports.io/football/teams/50.png",
    },
    fee: "€117.00M",
    market_value: "€75.00M",
    position: "Midfielder",
    nationality: "England",
    photo: "",
    league: "Premier League",
    season: "2025/2026",
  },
  {
    id: 8,
    player_name: "Antony",
    age: "25",
    date: "2025-08-30",
    from_club: {
      id: 113,
      name: "Ajax",
      logo: "https://media.api-sports.io/football/teams/94.png",
    },
    to_club: {
      id: 114,
      name: "Manchester United",
      logo: "https://media.api-sports.io/football/teams/33.png",
    },
    fee: "€95.00M",
    market_value: "€50.00M",
    position: "Forward",
    nationality: "Brazil",
    photo: "",
    league: "Premier League",
    season: "2025/2026",
  },
  {
    id: 9,
    player_name: "Darwin Núñez",
    age: "25",
    date: "2025-07-14",
    from_club: {
      id: 110,
      name: "Benfica",
      logo: "https://media.api-sports.io/football/teams/211.png",
    },
    to_club: {
      id: 115,
      name: "Liverpool",
      logo: "https://media.api-sports.io/football/teams/40.png",
    },
    fee: "€85.00M",
    market_value: "€70.00M",
    position: "Forward",
    nationality: "Uruguay",
    photo: "",
    league: "Premier League",
    season: "2025/2026",
  },
  {
    id: 10,
    player_name: "Aurélien Tchouaméni",
    age: "25",
    date: "2025-07-01",
    from_club: {
      id: 116,
      name: "AS Monaco",
      logo: "https://media.api-sports.io/football/teams/91.png",
    },
    to_club: {
      id: 102,
      name: "Real Madrid",
      logo: "https://media.api-sports.io/football/teams/541.png",
    },
    fee: "€80.00M",
    market_value: "€90.00M",
    position: "Midfielder",
    nationality: "France",
    photo: "",
    league: "La Liga",
    season: "2025/2026",
  },
];