// lib/mock-league-detail.ts
// Mock data for league detail — used as fallback when the RapidAPI quota is exceeded (429)

import type { ApiRapidLeagueDetail } from "@/types/api";

export const mockLeagueDetail: ApiRapidLeagueDetail = {
  id: 1,
  name: "Premier League",
  country: "England",
  logo: "https://media.api-sports.io/football/leagues/39.png",
  flag: "https://media.api-sports.io/flags/gb-eng.svg",
  seasonName: "2025/2026",
  seasonSlug: "2025-2026",
  teams: [
    {
      id: 50,
      name: "Manchester City",
      logo: "https://media.api-sports.io/football/teams/50.png",
      position: 1,
      points: 89,
      played: 38,
      won: 28,
      drawn: 5,
      lost: 5,
      goalsFor: 96,
      goalsAgainst: 34,
      goalDifference: 62,
    },
    {
      id: 42,
      name: "Arsenal",
      logo: "https://media.api-sports.io/football/teams/42.png",
      position: 2,
      points: 86,
      played: 38,
      won: 27,
      drawn: 5,
      lost: 6,
      goalsFor: 82,
      goalsAgainst: 29,
      goalDifference: 53,
    },
    {
      id: 33,
      name: "Manchester United",
      logo: "https://media.api-sports.io/football/teams/33.png",
      position: 3,
      points: 78,
      played: 38,
      won: 24,
      drawn: 6,
      lost: 8,
      goalsFor: 72,
      goalsAgainst: 41,
      goalDifference: 31,
    },
    {
      id: 49,
      name: "Chelsea",
      logo: "https://media.api-sports.io/football/teams/49.png",
      position: 4,
      points: 74,
      played: 38,
      won: 22,
      drawn: 8,
      lost: 8,
      goalsFor: 78,
      goalsAgainst: 39,
      goalDifference: 39,
    },
    {
      id: 40,
      name: "Liverpool",
      logo: "https://media.api-sports.io/football/teams/40.png",
      position: 5,
      points: 72,
      played: 38,
      won: 21,
      drawn: 9,
      lost: 8,
      goalsFor: 85,
      goalsAgainst: 38,
      goalDifference: 47,
    },
    {
      id: 47,
      name: "Tottenham Hotspur",
      logo: "https://media.api-sports.io/football/teams/47.png",
      position: 6,
      points: 65,
      played: 38,
      won: 19,
      drawn: 8,
      lost: 11,
      goalsFor: 74,
      goalsAgainst: 55,
      goalDifference: 19,
    },
    {
      id: 48,
      name: "West Ham United",
      logo: "https://media.api-sports.io/football/teams/48.png",
      position: 7,
      points: 58,
      played: 38,
      won: 16,
      drawn: 10,
      lost: 12,
      goalsFor: 56,
      goalsAgainst: 52,
      goalDifference: 4,
    },
    {
      id: 66,
      name: "Aston Villa",
      logo: "https://media.api-sports.io/football/teams/66.png",
      position: 8,
      points: 54,
      played: 38,
      won: 15,
      drawn: 9,
      lost: 14,
      goalsFor: 62,
      goalsAgainst: 58,
      goalDifference: 4,
    },
  ],
  topScorers: [
    {
      id: 1,
      playerName: "Erling Haaland",
      teamName: "Manchester City",
      teamLogo: "https://media.api-sports.io/football/teams/50.png",
      goals: 32,
      nationality: "Norway",
      photo: "",
    },
    {
      id: 2,
      playerName: "Harry Kane",
      teamName: "Tottenham Hotspur",
      teamLogo: "https://media.api-sports.io/football/teams/47.png",
      goals: 28,
      nationality: "England",
      photo: "",
    },
    {
      id: 3,
      playerName: "Mohamed Salah",
      teamName: "Liverpool",
      teamLogo: "https://media.api-sports.io/football/teams/40.png",
      goals: 24,
      nationality: "Egypt",
      photo: "",
    },
    {
      id: 4,
      playerName: "Bukayo Saka",
      teamName: "Arsenal",
      teamLogo: "https://media.api-sports.io/football/teams/42.png",
      goals: 18,
      nationality: "England",
      photo: "",
    },
    {
      id: 5,
      playerName: "Cole Palmer",
      teamName: "Chelsea",
      teamLogo: "https://media.api-sports.io/football/teams/49.png",
      goals: 16,
      nationality: "England",
      photo: "",
    },
  ],
};