// lib/mock-popular-leagues.ts
// Mock data for popular leagues — used as fallback when the RapidAPI quota is exceeded (429)

import type { ApiRapidLeague } from "@/types/api";

export const mockPopularLeagues: ApiRapidLeague[] = [
  {
    id: 1,
    name: "Premier League",
    country: "England",
    logo: "https://media.api-sports.io/football/leagues/39.png",
    flag: "https://media.api-sports.io/flags/gb-eng.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 2,
    name: "La Liga",
    country: "Spain",
    logo: "https://media.api-sports.io/football/leagues/140.png",
    flag: "https://media.api-sports.io/flags/es.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 3,
    name: "Serie A",
    country: "Italy",
    logo: "https://media.api-sports.io/football/leagues/135.png",
    flag: "https://media.api-sports.io/flags/it.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 4,
    name: "Bundesliga",
    country: "Germany",
    logo: "https://media.api-sports.io/football/leagues/78.png",
    flag: "https://media.api-sports.io/flags/de.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 5,
    name: "Ligue 1",
    country: "France",
    logo: "https://media.api-sports.io/football/leagues/61.png",
    flag: "https://media.api-sports.io/flags/fr.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 6,
    name: "UEFA Champions League",
    country: "Europe",
    logo: "https://media.api-sports.io/football/leagues/2.png",
    flag: "https://media.api-sports.io/flags/eu.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 7,
    name: "Eredivisie",
    country: "Netherlands",
    logo: "https://media.api-sports.io/football/leagues/88.png",
    flag: "https://media.api-sports.io/flags/nl.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 8,
    name: "Primeira Liga",
    country: "Portugal",
    logo: "https://media.api-sports.io/football/leagues/94.png",
    flag: "https://media.api-sports.io/flags/pt.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 9,
    name: "Süper Lig",
    country: "Turkey",
    logo: "https://media.api-sports.io/football/leagues/203.png",
    flag: "https://media.api-sports.io/flags/tr.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 10,
    name: "Jupiler Pro League",
    country: "Belgium",
    logo: "https://media.api-sports.io/football/leagues/144.png",
    flag: "https://media.api-sports.io/flags/be.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 11,
    name: "Scottish Premiership",
    country: "Scotland",
    logo: "https://media.api-sports.io/football/leagues/179.png",
    flag: "https://media.api-sports.io/flags/gb-sct.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 12,
    name: "Brasileirão Série A",
    country: "Brazil",
    logo: "https://media.api-sports.io/football/leagues/71.png",
    flag: "https://media.api-sports.io/flags/br.svg",
    season: "2025",
    seasonName: "2025",
    seasonSlug: "2025",
  },
  {
    id: 13,
    name: "Primera División",
    country: "Argentina",
    logo: "https://media.api-sports.io/football/leagues/128.png",
    flag: "https://media.api-sports.io/flags/ar.svg",
    season: "2025",
    seasonName: "2025",
    seasonSlug: "2025",
  },
  {
    id: 14,
    name: "MLS",
    country: "United States",
    logo: "https://media.api-sports.io/football/leagues/253.png",
    flag: "https://media.api-sports.io/flags/us.svg",
    season: "2025",
    seasonName: "2025",
    seasonSlug: "2025",
  },
  {
    id: 15,
    name: "Championship",
    country: "England",
    logo: "https://media.api-sports.io/football/leagues/40.png",
    flag: "https://media.api-sports.io/flags/gb-eng.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
  {
    id: 16,
    name: "Serie B",
    country: "Italy",
    logo: "https://media.api-sports.io/football/leagues/136.png",
    flag: "https://media.api-sports.io/flags/it.svg",
    season: "2025/2026",
    seasonName: "2025/2026",
    seasonSlug: "2025-2026",
  },
];