// lib/mock-match-data.ts
// Mock data for the match detail page — used in /app/match/page.tsx

import type { MatchDetailData } from "@/types/match-detail";

const mockMatchData: MatchDetailData = {
  header: {
    leagueName: "Premier League",
    leagueBadgeUrl: "",
    status: "finished",
    homeTeam: "Arsenal",
    awayTeam: "Chelsea",
    homeTeamBadgeUrl: "",
    awayTeamBadgeUrl: "",
    homeScore: 3,
    awayScore: 1,
    stadium: "Emirates Stadium",
    attendance: "60,704",
    referee: "Michael Oliver",
    var: "Stuart Attwell",
  },
  homeFormation: {
    formation: "4-3-3",
    players: [
      { name: "Raya", shirtNumber: 22, top: 92, left: 50 },
      { name: "White", shirtNumber: 4, top: 76, left: 15 },
      { name: "Saliba", shirtNumber: 2, top: 76, left: 38 },
      { name: "Gabriel", shirtNumber: 6, top: 76, left: 62 },
      { name: "Zinchenko", shirtNumber: 35, top: 76, left: 85 },
      { name: "Rice", shirtNumber: 41, top: 56, left: 25 },
      { name: "Odegaard", shirtNumber: 8, top: 56, left: 50 },
      { name: "Havertz", shirtNumber: 29, top: 56, left: 75 },
      { name: "Saka", shirtNumber: 7, top: 34, left: 20 },
      { name: "Martinelli", shirtNumber: 11, top: 34, left: 80 },
      { name: "Jesus", shirtNumber: 9, top: 30, left: 50 },
    ],
  },
  awayFormation: {
    formation: "4-2-3-1",
    players: [
      { name: "Petrovic", shirtNumber: 28, top: 92, left: 50 },
      { name: "James", shirtNumber: 24, top: 76, left: 15 },
      { name: "Thiago Silva", shirtNumber: 6, top: 76, left: 38 },
      { name: "Colwill", shirtNumber: 26, top: 76, left: 62 },
      { name: "Chilwell", shirtNumber: 21, top: 76, left: 85 },
      { name: "Caicedo", shirtNumber: 25, top: 56, left: 30 },
      { name: "Enzo", shirtNumber: 8, top: 56, left: 70 },
      { name: "Palmer", shirtNumber: 20, top: 40, left: 20 },
      { name: "Gallagher", shirtNumber: 23, top: 44, left: 50 },
      { name: "Mudryk", shirtNumber: 10, top: 40, left: 80 },
      { name: "Jackson", shirtNumber: 15, top: 30, left: 50 },
    ],
  },
  stats: [
    { label: "Possession", home: 58, away: 42 },
    { label: "xG", home: 2.4, away: 1.1 },
    { label: "Shots", home: 14, away: 8 },
    { label: "Shots on Target", home: 6, away: 3 },
    { label: "Big Chances", home: 4, away: 2 },
    { label: "Pass Accuracy", home: 88, away: 82 },
    { label: "Corners", home: 7, away: 4 },
  ],
  momentum: [
    { minute: 5, homeValue: 2, awayValue: 1 },
    { minute: 10, homeValue: 3, awayValue: 2 },
    { minute: 15, homeValue: 4, awayValue: 1 },
    { minute: 20, homeValue: 3, awayValue: 3 },
    { minute: 25, homeValue: 5, awayValue: 2 },
    { minute: 30, homeValue: 4, awayValue: 4 },
    { minute: 35, homeValue: 6, awayValue: 2 },
    { minute: 40, homeValue: 5, awayValue: 3 },
    { minute: 45, homeValue: 7, awayValue: 1 },
    { minute: 50, homeValue: 6, awayValue: 3 },
    { minute: 55, homeValue: 8, awayValue: 2 },
    { minute: 60, homeValue: 7, awayValue: 4 },
    { minute: 65, homeValue: 5, awayValue: 5 },
    { minute: 70, homeValue: 8, awayValue: 3 },
    { minute: 75, homeValue: 6, awayValue: 6 },
    { minute: 80, homeValue: 9, awayValue: 4 },
    { minute: 85, homeValue: 7, awayValue: 5 },
    { minute: 90, homeValue: 10, awayValue: 3 },
  ],
  timeline: [
    {
      id: "e1",
      minute: 12,
      player: "Gabriel Jesus",
      team: "home",
      type: "goal",
      assist: "Bukayo Saka",
      scoreHome: 1,
      scoreAway: 0,
    },
    {
      id: "e2",
      minute: 28,
      player: "Declan Rice",
      team: "home",
      type: "goal",
      assist: "Martin Odegaard",
      scoreHome: 2,
      scoreAway: 0,
    },
    {
      id: "e3",
      minute: 35,
      player: "Cole Palmer",
      team: "away",
      type: "yellow-card",
    },
    {
      id: "e4",
      minute: 45,
      player: "Nicolas Jackson",
      team: "away",
      type: "goal",
      assist: "Cole Palmer",
      scoreHome: 2,
      scoreAway: 1,
    },
    {
      id: "e5",
      minute: 52,
      player: "Gabriel Jesus",
      team: "home",
      type: "yellow-card",
    },
    {
      id: "e6",
      minute: 67,
      player: "Bukayo Saka",
      team: "home",
      type: "goal",
      assist: "Martin Odegaard",
      scoreHome: 3,
      scoreAway: 1,
    },
    {
      id: "e7",
      minute: 73,
      player: "Martin Odegaard",
      team: "home",
      type: "substitution",
      playerOff: "Jorginho",
    },
    {
      id: "e8",
      minute: 81,
      player: "Raheem Sterling",
      team: "away",
      type: "substitution",
      playerOff: "Mykhailo Mudryk",
    },
    {
      id: "e9",
      minute: 85,
      player: "Ben Chilwell",
      team: "away",
      type: "red-card",
    },
  ],
  players: [
    // Home team
    { id: 1, name: "David Raya", team: "home", rating: 7.2, goals: 0, assists: 0, shots: 0, passes: 32, tackles: 0 },
    { id: 2, name: "Ben White", team: "home", rating: 7.8, goals: 0, assists: 0, shots: 1, passes: 58, tackles: 4 },
    { id: 3, name: "William Saliba", team: "home", rating: 7.5, goals: 0, assists: 0, shots: 0, passes: 65, tackles: 3 },
    { id: 4, name: "Gabriel Magalhaes", team: "home", rating: 7.6, goals: 0, assists: 0, shots: 1, passes: 62, tackles: 5 },
    { id: 5, name: "Oleksandr Zinchenko", team: "home", rating: 7.4, goals: 0, assists: 0, shots: 0, passes: 72, tackles: 2 },
    { id: 6, name: "Declan Rice", team: "home", rating: 8.5, goals: 1, assists: 0, shots: 3, passes: 84, tackles: 6 },
    { id: 7, name: "Martin Odegaard", team: "home", rating: 8.8, goals: 0, assists: 2, shots: 4, passes: 91, tackles: 1 },
    { id: 8, name: "Kai Havertz", team: "home", rating: 7.3, goals: 0, assists: 0, shots: 2, passes: 45, tackles: 2 },
    { id: 9, name: "Bukayo Saka", team: "home", rating: 9.0, goals: 1, assists: 1, shots: 5, passes: 52, tackles: 3 },
    { id: 10, name: "Gabriel Martinelli", team: "home", rating: 7.1, goals: 0, assists: 0, shots: 2, passes: 38, tackles: 1 },
    { id: 11, name: "Gabriel Jesus", team: "home", rating: 8.2, goals: 1, assists: 0, shots: 4, passes: 29, tackles: 0 },
    // Away team
    { id: 12, name: "Djordje Petrovic", team: "away", rating: 6.5, goals: 0, assists: 0, shots: 0, passes: 28, tackles: 0 },
    { id: 13, name: "Reece James", team: "away", rating: 6.8, goals: 0, assists: 0, shots: 1, passes: 45, tackles: 3 },
    { id: 14, name: "Thiago Silva", team: "away", rating: 7.0, goals: 0, assists: 0, shots: 0, passes: 52, tackles: 2 },
    { id: 15, name: "Levi Colwill", team: "away", rating: 6.7, goals: 0, assists: 0, shots: 0, passes: 48, tackles: 3 },
    { id: 16, name: "Ben Chilwell", team: "away", rating: 5.5, goals: 0, assists: 0, shots: 0, passes: 35, tackles: 1 },
    { id: 17, name: "Moises Caicedo", team: "away", rating: 7.2, goals: 0, assists: 0, shots: 1, passes: 61, tackles: 5 },
    { id: 18, name: "Enzo Fernandez", team: "away", rating: 7.1, goals: 0, assists: 0, shots: 2, passes: 68, tackles: 3 },
    { id: 19, name: "Cole Palmer", team: "away", rating: 7.8, goals: 0, assists: 1, shots: 3, passes: 42, tackles: 1 },
    { id: 20, name: "Conor Gallagher", team: "away", rating: 7.3, goals: 0, assists: 0, shots: 2, passes: 55, tackles: 4 },
    { id: 21, name: "Mykhailo Mudryk", team: "away", rating: 6.4, goals: 0, assists: 0, shots: 1, passes: 28, tackles: 0 },
    { id: 22, name: "Nicolas Jackson", team: "away", rating: 6.9, goals: 1, assists: 0, shots: 3, passes: 22, tackles: 0 },
  ],
};

export default mockMatchData;